name: 10) Test writing to secrets

on:
  workflow_dispatch:
  
jobs:
  test_action:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate gh CLI using PAT
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: gh auth login --with-token

      - name: Set a new GitHub secret
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: gh secret set NEW_SECRET -b"super_secret_value"
        
