name: 10) Test writing to secrets

on:
  workflow_dispatch:
  
jobs:
  test_action:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Clear existing GH token
        run: export GH_TOKEN=

      - name: Authenticate gh CLI using PAT
        run: echo ${{ secrets.PAT }} | gh auth login --with-token

      - name: Set and mask secret
        run: |
          # Mask the secret to prevent it from being printed in the logs
          echo "::add-mask::$MY_SECRET"

          # Define the secret
          MY_SECRET="super_secret_value"

          # Example usage of the secret
          echo "The secret is $MY_SECRET"

      - name: Set a new GitHub secret
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: gh secret set NEW_SECRET -b"super_secret_value"
        
