name: 10) Test writing to secrets

on:
  workflow_dispatch:
  
jobs:
  test_action:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate gh CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Fetch public key
        run: gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/jonnyry/github-actions-test/actions/secrets/public-key"

      - name: Set a new GitHub secret
        run: gh secret set NEW_SECRET -b"super_secret_value"
        
