name: 11) Secrets with defaults

on:
  workflow_dispatch:
  
jobs:
  test_action:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SECRET_NOT_DEFINED: ${{ secrets.SECRET_NOT_DEFINED }}
        run: echo "$SECRET_NOT_DEFINED"

        
