name: 11) Secrets with defaults

on:
  workflow_dispatch:
  
jobs:
  test_secret_not_defined:
    name: Test secret not defined
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SECRET_NOT_DEFINED: ${{ secrets.SECRET_NOT_DEFINED }}
        run: echo Value of SECRET_NOT_DEFINED is "$SECRET_NOT_DEFINED"

  test_secret_not_defined_with_default:
    name: Test secret not defined with default
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SECRET_NOT_DEFINED: ${{ secrets.SECRET_NOT_DEFINED || 'Default secret value' }}
        run: echo Value of SECRET_NOT_DEFINED is "$SECRET_NOT_DEFINED"
        
