# File: .github/workflows/workflow.yml

on: workflow_dispatch

name: 5) Test masking log output

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
    
    - run: |
        echo "This is A PUBLIC STRING"
        echo "This is MY PRIVATE STRING"
        echo "Adding mask for MY PRIVATE STRING..."
        echo "::add-mask::MY PRIVATE STRING"
        echo "This is A PUBLIC STRING"
        echo "This is MY PRIVATE STRING"

    - run: |
        echo "This is MY PRIVATE STRING"

  job2:
    runs-on: ubuntu-latest
    steps:
    
    - run: |
        echo "This is A PUBLIC STRING"
        echo "This is MY PRIVATE STRING"
