# File: .github/workflows/workflow.yml

on: workflow_dispatch

name: 6) Test build vars

jobs:

  create-some-vars:
    runs-on: ubuntu-latest
    steps:
    
    - run: |
        echo GITHUB_REPOSITORY = ${GITHUB_REPOSITORY}
        echo ${GITHUB_REPOSITORY#*/}
        echo GITHUB_REF = ${GITHUB_REF#refs/heads/}
        echo GITHUB_SHA = ${GITHUB_SHA:0:7}
        echo BUILD_DATE = $(date '+%Y-%m-%dT%H:%M:%S')

  read-some-vars:
    runs-on: ubuntu-latest
    steps:
    
    - run: |
        echo "This is A PUBLIC STRING"
        echo "This is MY PRIVATE STRING"
