name: 8) Test exit code escaping

on:
  workflow_dispatch:
  
jobs:
  test_action:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - name: Setup BUILD_TAG environment variable
        run: |
          for i in {1..3}; do
            echo a && ec=0 && break || ec="$?"
          done

          echo Value of ec is $ec

          # asjijiasjias || ec=$?

          echo Value of ec is $ec

          (exit "$ec")

