name: 9) Test expressions

on:
  workflow_dispatch:
  
jobs:
  test_action:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": ${{ secret.TEST_CLIENT_ID }},
              "clientSecret": ${{ secret.TEST_CLIENT_SECRET }},
              "subscriptionId": "${{ secret.TEST_SUBSCRIPTION }},
              "tenantId": ${{ secret.TEST_TENANT_ID }}
            }
  
