# File: .github/workflows/workflow.yml

on: workflow_dispatch

name: 5) Test AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        az account show
        az webapp list --query "[?state=='Running']"
