name: Test - Exists both branches, different steps on each branch

on:
  workflow_dispatch:
  
jobs:
  test_action:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - name: Setup BUILD_TAG environment variable
        run: echo "BUILD_TAG=\"${GITHUB_REPOSITORY#*/} | Branch ${GITHUB_REF#refs/heads/} | SHA ${GITHUB_SHA:0:7} | BuildTime $(date '+%Y-%m-%dT%H:%M:%S')\"" >> $GITHUB_ENV
      - name: Print the BUILD_TAG
        run: echo ${{ env.BUILD_TAG }}
      - name: Print different step for main
        run: echo "This is the YAML action file running from the main branch"
